### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by SaravanaKumarVelliyangiri** [SAPDocuments/Issues#137] opened 2021-02-10 01:40 UTC
Tutorial: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html
--------------------------

In Step 8 point 3, I 'm getting error response which is shown below.
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
    <soap:Body>
        <soap:Fault>
            <soap:Code>
                <soap:Value>soap:Receiver</soap:Value>
            </soap:Code>
            <soap:Reason>
                <soap:Text xml:lang="en">An internal error occurred during message processing. For error details check the System Logs Monitor in https://71002066trial.it-cpitrial03.cfapps.ap21.hana.ondemand.com:443/itspaces/shell/monitoring/SystemLogs</soap:Text>
            </soap:Reason>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>

Can you kindly help to understand the issue here and fix the same?

**Comment by gauthamkrishna-sap** [comment] 2021-02-10 14:44
Hi,
We are in the process of updating this tutorial and the associated mission. We will release a new version in a few weeks. Apologies for the inconvenience. 
Best Regards, Gautham

**Comment by MichaelCzcz** [comment] 2021-03-16 07:36
@gauthamkrishna-sap Any updates?

**Comment by thecodester** [comment] 2021-04-04 07:10
@gauthamkrishna-sap ?

**Comment by jmalla** [comment] 2021-04-17 04:39
I have the same issue.  I think it is a permissions issue.  I think the user needs to have the role ESBMessaging.send.  But I do not see how I can add this role.

The issue is that with the BTP trial account and CPI, we do not have access to see the SystemLogs.

Regards,
Jay

**Comment by jmalla** [comment] 2021-04-17 06:32
Another person had the same issue and found a work around.  However, that did not work for me:
Assign ESBMessaging.send role #5519
https://github.com/SAPDocuments/Tutorials/issues/5519

**Comment by jmalla** [comment] 2021-04-19 17:33
I got this to work.  For the CPI runtime instance - the steps were missing to get the ESBMessaging.send.  You can see these steps in the YouTube video: 
SAP Integration Suite Intro Part 1.3 Security
https://youtu.be/L1hgBnbqYS4

Also, I changed the mail channel that uses my Gmail account by referring to this really helpful blog - 
Mail Receiver Adapter in SAP – CPI : A step by step Guide!

https://recodehive.com/mail-receiver-adapter-in-sap-cpi-a-step-by-step-guide/

**Comment by MichaelCzcz** [comment] 2021-04-28 06:58
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2021-04-28 06:58 UTC
