### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by DanGielman** [SAPDocuments/Issues#48] opened 2021-01-12 14:52 UTC
Tutorial: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

For some reason, the table community does not appear to me, despite of passing through all the steps. 

<img width="928" alt="Screen Shot 2021-01-12 at 11 52 18" src="https://user-images.githubusercontent.com/55021993/104330266-97b1b700-54cc-11eb-9945-8c7aa558b02c.png">

**Comment by jung-thomas** [comment] 2021-01-12 15:50
This seems to be a duplicate of  Issue #43 .  I'm closing this one as its the exactly same question as your earlier issue. Please do return to that issue and provide us with more details as requested.  Without some view of your project and/or deployment log its impossible to be able to assist you.

**Closed by jung-thomas** 2021-01-12 15:50 UTC
