### ISSUE TITLE
Configure Business Rules, Workflow and Process Visibility

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Issues#210] opened 2021-03-09 16:21 UTC
Tutorials: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-configure.html
--------------------------

Step 6: Build and deploy workflow
Screenshot needs to be updated: Now the mta build option is changed from 'Build MTA' to 'Build MTA Project'. Also other option have been changed.

Expected Result:
![image](https://user-images.githubusercontent.com/50734023/110502765-7f9f9200-8121-11eb-9158-9c1c0a7cd98a.png)

Actual Result:
![image](https://user-images.githubusercontent.com/50734023/110502802-87f7cd00-8121-11eb-8389-b02f5f6658ab.png)

**Comment by ArchanaShukla** [comment] 2021-04-05 10:08
Hello Nidhi, can you let me know which data center you see this, because for me I still the same old options. I even created the new workspace: 

![image](https://user-images.githubusercontent.com/34297037/113563241-fc406600-9624-11eb-8a6e-66610ae94838.png)

**Comment by FarozanFarman** [comment] 2021-04-12 11:27
Hi @ArchanaShukla,

I think the issue is fixed. In this execution, I didn't get the options as of what Nidhi got. I can see the options as yours in all three regions.

Thanks and Regards,
Farozan

**Comment by ArchanaShukla** [comment] 2021-04-12 11:33
Thanks for confirming. closing the issue now.

**Closed by ArchanaShukla** 2021-04-12 11:33 UTC
Labels: Low-Prio, SCPTest-2103A, SCPTest-eboard, SCPTest-trial1, SCPTest-trial2, SCPTest-trial3
