### ISSUE TITLE
Create a List Report Object Page App with SAP Fiori Tools

### ISSUE THREAD

**Issue by bri-davis** [SAPDocuments/Issues#96] opened 2021-01-22 18:28 UTC
Group: https://developers.sap.com/group.fiori-tools-lrop.html
--------------------------
I am unable to access the Odata URL in "Create a List Report Object Page with SAP Fiori App" developer guide with the following error: 

Guide
![guide](https://user-images.githubusercontent.com/37200864/105530291-92ffb680-5cb5-11eb-9f04-69baf835e142.png)

Error
![error](https://user-images.githubusercontent.com/37200864/105530298-95faa700-5cb5-11eb-8512-e4f37f8be663.png)

I'm believe the Odata URL might be down from this guide.

**Comment by thecodester** [comment] 2021-01-24 14:59
@jung-thomas Here is another issue with Gateway service.

**Comment by thecodester** [comment] 2021-01-24 15:13
@bri-davis I see on the sign-in page that there is planned maintenance from Jan. 22-24. Please try again tomorrow and let us know if it works. Sorry for the inconvenience.

This seems to be a duplicate of issue https://github.com/SAPDocuments/Issues/issues/97 so I will close this one.

**Closed by thecodester** 2021-01-24 15:13 UTC
