### ISSUE TITLE
Req. Product Details - Screenshot not loading 

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#543] opened 2021-08-10 11:57 UTC
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
Step 1: Access your Cloud Integration workspace

the attached Screenshot is not loading. Please refer to the screenshot:
![image](https://user-images.githubusercontent.com/66831161/128862521-78d091ee-7478-45a5-939a-99a944db438d.png)
Please check the issue.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2108A
Scenario Label: SCPTest-cloudin
Landscape Label: US10,EU10 & AP
Prio: High-prio

**Comment by Karunaharan** [comment] 2021-08-11 07:02
@MichaelCzcz - could you please help me resolving the issue? I'm not sure what I missed in the .md file?

**Comment by MichaelCzcz** [comment] 2021-08-11 07:17
@Karunaharan Simply remove the indentation for the image.

**Comment by Karunaharan** [comment] 2021-08-11 07:24
Thank you @MichaelCzcz 

@i353590 - the issue is fixed now. Will be published very soon.

**Closed by Karunaharan** 2021-08-11 07:24 UTC
Labels: High-Prio, SCPTest-trial1, SCPTest-trial2, SCPTest-trial3, SCPTest-cloudin, SCPTest-2108A

**Comment by i353590** [comment] 2021-08-13 08:37
The screenshot is still not loading.
if the change is not pushed yet, by when can we expect the fix.?

thanks,
Shubham

**Comment by Karunaharan** [comment] 2021-08-13 08:48
Hi, yes the change is not pushed yet. Waiting for other feedback from you/your team, if any.
