### ISSUE TITLE
Get Started with SAP Web Analytics | Internal Incident: 2180170193

### ISSUE THREAD

**Issue by vinay31** [SAPDocuments/Issues#383] opened 2021-05-21 10:35 UTC
Mission: https://developers.sap.com/mission.cp-web-analytics-get-started.html
--------------------------

My subaccount details: 
my user : vinay.godugu@itelligencegroup.com
Subaccount: trial
Subaccount ID:
bec16ccd-309e-4e17-aee1-545a7378948a
Tenant ID:
bec16ccd-309e-4e17-aee1-545a7378948a
Subdomain:
01eff9fbtrial
Org Name:
01eff9fbtrial
Org ID:
8e561976-c442-4dce-b677-7d67841ab067

API Endpoint:
https://api.cf.eu10.hana.ondemand.com

------------------------------------------------------------
My application URL: https://01eff9fbtrial.web-analytics.cfapps.eu10.hana.ondemand.com/index.html

The issue is am unable to create spaces and it shows authorization missing. below are the details
**POST URL** : https://01eff9fbtrial.web-analytics.cfapps.eu10.hana.ondemand.com/api/tenants
**Method** : POST
**Payload** : {"name":"Test","description":"test space","userId":"","userName":"","visitorAnonymitySettings":false,"admins":[{"userId":"vinay.godugu@itelligencegroup.com","name":"VinayG","active":true}],"active":1,"customerId":"testCustomer"}
**Response** : {"response":{"CODE":40305,"MESSAGE":"You do not have necessary authorization to perform the requested action."}}
![image](https://user-images.githubusercontent.com/2324128/119124298-22dc2400-ba4e-11eb-826e-98d014977962.png)

Please help me. We are in a process of talking about this to our customers. 

I have also raised with SAP Community, still no luck. appreciate your support. 
https://answers.sap.com/questions/13387138/sap-web-analytics-authorization-issue.html

Cheers,
Vinay

**Comment by Vikramkulkarni01** [comment] 2021-05-21 10:57
Hi Vinay, 

Thanks for reaching out to us. 
 
With reference to your concern, I can see that you are facing an issue in authorizing space and you are unable to add space as well. 

I will be now involving the expert team to get this issue checked for your trial instance. I will be working closely with them and keep you posted with an update. 

I truly appreciate your patience. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment] 2021-05-26 08:25
Hi @vinay31, 
With reference to your concern, our internal team is analyzing the logs and they are performing a deeper investigation. 

I am working closely with the team and keep you posted with an update. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment] 2021-05-26 09:35
Hi @vinay31, 

With reference to your concern, I received an update from my internal team they confirmed an issue that you are facing and they will be providing the fix by end of this week. I kindly request you to try the same after 30th May 2021.

Since there are no actions required from our end I will be closing this issue. 

Please feel free to reopen it if the issue persists. 

Regards, 
Vikram Kulkarni

**Closed by Vikramkulkarni01** 2021-05-26 09:35 UTC
Labels: SAP Web Analytics Trial

**Comment by vinay31** [comment] 2021-05-31 04:10
Hi Vikram, 

Thank you. I tried today, but still same behaviour. Please suggest. 

Cheers,
Vinay

**Comment by Vikramkulkarni01** [comment] 2021-05-31 04:41
Hi Vinay,
Thanks for the feedback.

You just need to unsubscribe and re-subscribe to the service then only it will work.

Could you please follow the below steps:


  1.   Unsubscribe and re-subscribe to the service of you would have already subscribed.
  2.  If the above step doesn’t work, delete the sub account, create new one, and subscribe to the service  once again.

Per recommendation, you must need to perform the step 1 to work on the deployed fix.

Let me know if this works for you and I will be happy to assist you.

Thanks and Regards,
Vikram Kulkarni,
Information Architect and User Assistance Lead, SAP BTP.

________________________________

**Comment by vinay31** [comment] 2021-05-31 04:53
Thanks, Vikram. It worked now. Appreciate you and your team for this fix. Have a good week ahead.

**Comment by Vikramkulkarni01** [comment] 2021-05-31 04:56
Thanks for the confirmation Vinay.

I truly appreciate your feedback.

Thanks and Regards,
Vikram Kulkarni,
Information Architect and User Assistance Lead, SAP BTP.

________________________________
