### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by tufa-github** [SAPDocuments/Issues#15] opened 2020-12-28 17:32 UTC
Tutorial: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------

Hi,

I'm using the tutorialto study SAP HANA cloud.  It is clear and practical for a beginner. But I got a issue in Step 7: Create database artifacts. I aways got No service instances found if I bind HDI_DB after clone the git project to SAP Business Application Studio. 
A HANA Cloud instance has been created in my trial account successfully.  
The Provider of my trial subaccount is Amazon Web Services (AWS) and Region is: Europe (Frankfurt) - AWS

could you please help me to fix the issue? 

Thanks!

**Comment by jung-thomas** [comment] 2020-12-28 17:38
What exactly are you seeing when you perform the bind?  Do you get the command window at the top of the screen?  Does the command window say no service instances found?  A screenshot of what you are seeing at this step would be helpful.  Are you logged into CF successfully (from previous steps)? From the console what do you see if you issue a "cf services" command?

**Comment by tufa-github** [comment] 2020-12-28 17:42
there are no command windows at the top of screen. the message shows on the right bottom. see the scrrenshot
![image](https://user-images.githubusercontent.com/76044478/103233003-3f12e380-493c-11eb-927d-57abf52f4269.png)

**Comment by jung-thomas** [comment] 2020-12-28 17:44
Can you try the "cf services" command. I think this dialog is trying to tell you that it couldn't find the HANA Cloud service instance in your target org/space. Are you sure you are successfully logged into Cloud Foundry (status in the bottom left corner of the screen) from two steps back?

**Comment by tufa-github** [comment] 2020-12-28 18:00
I think I'm correct logged into CF 
![image](https://user-images.githubusercontent.com/76044478/103233588-c57bf500-493d-11eb-9e6a-a301d793ff24.png)

BTW: where is the "cf services" command

**Comment by jung-thomas** [comment] 2020-12-28 18:05
Type the command "cf services" in the terminal window. If you need to open a terminal use Terminal->New Terminal from the top menu.

**Comment by jung-thomas** [comment] 2020-12-28 19:01
I'm not able to recreate this issue in my account with the same project.  So I've notified the development team within SAP that is responsible for this tooling.

**Comment by tufa-github** [comment] 2020-12-29 11:28
Hi Thomas,

I checked my configuration for HANA Cloud. It seem all settings are correct. see screenshot below Do I need install the DigiCertGlobalRootCA.crt for the connection as meantioned in https://blogs.sap.com/2020/06/26/connect-hana-cloud-service-instance-with-sap-business-application-studio/
![image](https://user-images.githubusercontent.com/76044478/103280499-daee2f00-49d0-11eb-9bb9-564afb2d8b19.png)
![image](https://user-images.githubusercontent.com/76044478/103280521-e80b1e00-49d0-11eb-9aa2-29df2082c6dc.png)

**Comment by jung-thomas** [comment] 2020-12-29 13:07
I spoke with development and confirmed that this is a bug in the tooling itself. It occurs when you have no existing HDI container service instances in your account.  Therefore the dialog isn't shown.  But this is in error because the same dialog would be used to also create a new instance.  The bug has been fixed in development is pending a hot fix to move it production and the trial landscape. 

In the mean time there is a workaround. You can create the HDI service instance manually from the terminal.  Use the command
`cf create-service hana hdi-shared my-hdi`
Give it a few minutes to create. You can check the status with the command `cf services` .  Once fully created, you can continue with this step.  But instead of choosing "Create a new service instance" you can just select the service instance you just created manually.

**Closed** 2020-12-29 14:21 UTC

**Comment by tufa-github** [comment] 2020-12-30 15:38
Thank you very much for work out the issue 👍. The next steps work fine after creating and bind the HDI container manually.
