### ISSUE TITLE
Create a Chatbot that Lets Customers Track Packages

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#283] opened 2021-03-30 21:35 UTC
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html
--------------------------

When I test the Regex Pattern I get an error message that I have no match. Tried opening it incognito ,but no luck. 

![image](https://user-images.githubusercontent.com/29966401/113060184-cfe3ae80-920c-11eb-9c32-6c26fc71d438.png)

**Comment by thecodester** [comment] 2021-03-31 12:01
I assume the issue is there are extra spaces at the end of the pattern. This is my fault because they exist in the code block where you copy the pattern from. I have fixed in the tutorial. Let me know if this solves the issue.

**Comment by advit-ramesh** [comment] 2021-03-31 21:35
Thanks. It works now.

**Comment by thecodester** [comment] 2021-04-04 06:59
:-)

**Closed by thecodester** 2021-04-04 06:59 UTC
